Feature/extras
andrey-dihtiarov/wizard-form-react pull request #11
Opened 2021-06-14 13:20 UTC by andrey-dihtiarov

2021-06-15 13:29 UTC, oleksandrbazil requested changes

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/ImageUploader/CropModal/index.jsx
> +          croppedAreaPixels.x,
почему решил без деструктуризации?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/ImageUploader/CropModal/index.jsx
> +      canvasRef.current.toBlob((file) => {
можно ли написать в 1 строчку?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/ImageUploader/CropModal/index.jsx
> +      }, 'image/jpg');
а почему решил принудительно конвертировать в image/jpg?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/ImageUploader/CropModal/index.jsx
> +          Crop
почему бы не передать title?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/ImageUploader/CropModal/index.jsx
> +        width={croppedAreaPixelsState.width}
почему так?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/ImageUploader/index.jsx
> +  const [image, setImage] = useState();
а в чем разница между photo & image?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/ImageUploader/index.jsx
> +      reader.onloadend = (e) => {
можно ли написать короче?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/ImageUploader/index.jsx
> +      const [file] = event.target.files;
логичней было бы назвать firstFile

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/ImageUploader/index.jsx
> +  const updateCroppedImageFile = useCallback(
почитай [про хуки](https://reactjs.org/docs/hooks-reference.html#usecallback) и расскажи мне можно ли использовать async в хуках?
Напиши как прочтешь плз

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/ImageUploader/index.jsx
> +          src={photo && URL.createObjectURL(photo)}
есть предположение, что тут будет утечка памяти, потому что https://developer.mozilla.org/ru/docs/Web/API/URL/createObjectURL, было бы здорово если бы ты это проверил есть ли утечка

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/Loader/index.jsx
> +      <div />
однако здравствуйте, а что это?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/Loader/index.jsx
> +  isFixed: true,
не надо так писать, лучше что бы по умолчанию флаг был false
а если где-то нужно поставить true то мы прокинем его

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/Pagination/index.jsx
> +  const [skipState, setSkipState] = useState(skip);
что такое skipState?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/Pagination/index.jsx
> +  }, [total]);
что будет если перейти на страницу X и удалить какую-то запись?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/Pagination/index.jsx
> +  const [limitState] = useState(limit);
что такое limitState?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/Search/index.jsx
> +Search.propTypes = {
забыл описать searchQuery

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/Search/index.jsx
> +    const {
а нельзя это сделать сразу при получении параметров?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/components/Search/index.jsx
> +      params.append('search', debouncedQuery);
не совсем понимаю как это работает. debouncedQuery это функция или значение?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/db/UsersTable/index.js
> +  // getUsers() {
закоментированный код - мертвый код, особенно без TODO комментариев

2021-06-15 13:29 UTC, oleksandrbazil commented on src/db/UsersTable/index.js
> +    const lcQuery = query.toLowerCase();
что такое lcQuery? как будет называться переменная если мы в дальнейшем будем использовать .toUpperCase()?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/db/UsersTable/index.js
> +    const testRegex = new RegExp(lcQuery, 'i');
нужна ли эта переменная вовсе?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/db/UsersTable/index.js
> +  getUsers(skip, limit, query) {
по мере добавления параметров количество аргументов будет расти, в этом случае лучше сразу использовать объект params

2021-06-15 13:29 UTC, oleksandrbazil commented on src/hooks/useDebounce/index.js
> +export default (value, timeout) => {
а где параметры по умолчанию?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/hooks/useQuery/index.js
> +const useQuery = () => new URLSearchParams(useLocation().search);
почему решил вынести в кастомный хук?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/pages/users/UsersPage/UsersTable/index.jsx
> +import Loader from '../../../../components/Loader';
группируй импорты

2021-06-15 13:29 UTC, oleksandrbazil commented on src/pages/users/UsersPage/UsersTable/index.jsx
> +            <td>
как повлияет разное количество ячеек в tbody и thead на отображение таблицы?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/pages/users/UsersPage/UsersTable/index.jsx
> +              index={index}
а зачем передаешь туда индекс?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/db/UsersTable/index.js
> +        this.db[this.table]
а сможешь сделать так что бы был 1 Promise запрос?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/db/UsersTable/index.js
> +      this.db[this.table].offset(skip).limit(limit).toArray(),
зачем этот блок?можно ли найти пользователей так что бы не писать для каждого случая offset/limit?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/pages/users/UsersPage/index.jsx
> +const SKIP = 0;
а разве skip должен быть константой? или мы когда-то будем пропускать первых 2 пользователя?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/db/UsersTable/index.js
> +    if (query) {
что будет если skip или limit будут строкой? если не передадут оба? или только 1?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/pages/users/UsersPage/index.jsx
> +        <Pagination onNavigation={onNavigation} total={totalUsers} skip={SKIP} limit={LIMIT} />
а зачем передавать Skip если мы на первой странице?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/store/user.js
> +export const fetchUsers = createAsyncThunk('user/fetchUsers', async ({ skip, limit, query }) => {
есть ощущение что тут не нужны thunk.
Скажи плз когда нам нужно использовать Thunk?

2021-06-15 13:29 UTC, oleksandrbazil commented on src/utils/accountGenerator.js
> +import avatar from '../assets/mockImages/avatar.jpg';
используй какой-то сервис для генерации картинок

2021-06-15 13:29 UTC, oleksandrbazil commented on src/utils/accountGenerator.js
> +    birthDate: getRandomDate(new Date(1930, 1, 1), new Date(2000, 1, 1)).toISOString(),
почему первая дата не toISOString?

2021-06-15 14:18 UTC, andrey-dihtiarov commented on src/components/ImageUploader/CropModal/index.jsx
> +          croppedAreaPixels.x,
Забыл использовать здесь деструктуризацию. Переписал

2021-06-15 14:19 UTC, andrey-dihtiarov commented on src/components/ImageUploader/CropModal/index.jsx
> +      canvasRef.current.toBlob((file) => {
Можно. Переписал

2021-06-15 14:19 UTC, andrey-dihtiarov commented on src/components/ImageUploader/CropModal/index.jsx
> +      }, 'image/jpg');
Даже не знаю почему. Убрал это. По умолчанию делает ПНГ

2021-06-15 14:23 UTC, andrey-dihtiarov commented on src/components/ImageUploader/CropModal/index.jsx
> +          Crop
Сделал

2021-06-15 14:34 UTC, andrey-dihtiarov commented on src/components/ImageUploader/CropModal/index.jsx
> +        width={croppedAreaPixelsState.width}
Можно было через const canvas = document.createElement('canvas') сделать, но подумал, что через реф будет правильнее.

2021-06-15 14:38 UTC, andrey-dihtiarov commented on src/components/ImageUploader/index.jsx
> +  const [image, setImage] = useState();
Photo - файл, а image - ref img элемента. В общем я хочу попробовать переписать это получше

2021-06-15 14:39 UTC, andrey-dihtiarov commented on src/components/ImageUploader/index.jsx
> +      reader.onloadend = (e) => {
 Переписал

2021-06-15 14:39 UTC, andrey-dihtiarov commented on src/components/ImageUploader/index.jsx
> +      const [file] = event.target.files;
Согласен

2021-06-15 14:44 UTC, andrey-dihtiarov commented on src/components/Loader/index.jsx
> +      <div />
withOverlay - для оверлея который закрывает все пространство. isFixed - для фиксирования лоадера ровно по центру экрана, т.е. делаем его fixed. Наверное все это лишнее.

2021-06-15 14:49 UTC, andrey-dihtiarov commented on src/components/Loader/index.jsx
> +  isFixed: true,
Хорошо

2021-06-15 14:52 UTC, andrey-dihtiarov commented on src/components/Pagination/index.jsx
> +  const [limitState] = useState(limit);
Забыл убрать лимит стейт. Он здесь лишний. Я никак не изменяю лимит. Лимит используется для того, чтобы взять определенный лимит юзеров

2021-06-15 14:52 UTC, andrey-dihtiarov commented on src/components/Pagination/index.jsx
> +  const [skipState, setSkipState] = useState(skip);
Количество записей которые мы должны пропустить

2021-06-16 05:09 UTC, oleksandrbazil commented on src/components/ImageUploader/CropModal/index.jsx
> +      }, 'image/jpg');
так может нужно использовать тот же тип который у водящего файл? не будет ли это логичней?

2021-06-16 05:10 UTC, oleksandrbazil commented on src/components/ImageUploader/CropModal/index.jsx
> +        width={croppedAreaPixelsState.width}
мне не очень понятно почему тут не используешь деструктуризацию?

2021-06-16 05:11 UTC, oleksandrbazil commented on src/components/ImageUploader/index.jsx
> +  const [image, setImage] = useState();
смотри если я не понял что это, то вероятней всего ты выбрал неудачное имя переменной. Попробуй переименовать так что бы передать суть значения

2021-06-16 05:12 UTC, oleksandrbazil commented on src/components/Loader/index.jsx
> +      <div />
мне не понятно зачем нам 4 пустых div ?

2021-06-16 05:14 UTC, oleksandrbazil commented on src/components/Pagination/index.jsx
> +  const [skipState, setSkipState] = useState(skip);
дай переменным другое название которое будет более точно отображать суть 
https://translate.google.com/?hl=ru&sl=en&tl=ru&text=limit%20State%0Askip%20State&op=translate

2021-06-16 05:15 UTC, oleksandrbazil commented on src/components/Pagination/index.jsx
> +  const [limitState] = useState(limit);
тогда удаляй это

2021-06-16 07:25 UTC, andrey-dihtiarov commented on src/components/Loader/index.jsx
> +      <div />
Для лоадера нужно 4 пустых дива. Я мап сделал на 4 дива

2021-06-16 10:44 UTC, andrey-dihtiarov commented on src/components/ImageUploader/CropModal/index.jsx
> +      }, 'image/jpg');
Переделал это

2021-06-16 10:45 UTC, andrey-dihtiarov commented on src/components/ImageUploader/CropModal/index.jsx
> +        width={croppedAreaPixelsState.width}
А, ясно. Добавил деструктуризацию

2021-06-16 10:46 UTC, andrey-dihtiarov commented on src/components/ImageUploader/index.jsx
> +  const [image, setImage] = useState();
Да, бывает тяжело подобрать название переменной правильно. Тут действительно не понятно. Я переделал этот компонент, теперь остался только image

2021-06-16 10:46 UTC, andrey-dihtiarov commented on src/components/ImageUploader/index.jsx
> +  const updateCroppedImageFile = useCallback(
Это мы уже обсудили

2021-06-16 10:51 UTC, andrey-dihtiarov commented on src/components/ImageUploader/index.jsx
> +          src={photo && URL.createObjectURL(photo)}
В перфоманс мониторе хрома смотрел, вроде все ок. Но я все равно переделал компонент чтобы не использовать этот метод

2021-06-16 11:11 UTC, andrey-dihtiarov commented on src/components/Pagination/index.jsx
> +  }, [total]);
Вернется на первую. Исправил это

2021-06-16 11:27 UTC, andrey-dihtiarov commented on src/components/Search/index.jsx
> +Search.propTypes = {
Добавил

2021-06-16 11:27 UTC, andrey-dihtiarov commented on src/components/Search/index.jsx
> +      params.append('search', debouncedQuery);
Это значение

2021-06-16 11:31 UTC, andrey-dihtiarov commented on src/db/UsersTable/index.js
> +    const testRegex = new RegExp(lcQuery, 'i');
Не нужна, я забыл её убрать

2021-06-16 11:33 UTC, andrey-dihtiarov commented on src/hooks/useDebounce/index.js
> +export default (value, timeout) => {
Ну на value не знаю зачем добавлять параметр по умолчанию, а  за timeout согласен, добавил

2021-06-16 11:36 UTC, andrey-dihtiarov commented on src/hooks/useQuery/index.js
> +const useQuery = () => new URLSearchParams(useLocation().search);
![Screenshot 2021-06-16 at 14 34 49](https://user-images.githubusercontent.com/82100556/122212079-1eb9ef80-ceb0-11eb-8655-b363eadd2632.png)
 Решил сделать как в доке было

2021-06-16 11:42 UTC, andrey-dihtiarov commented on src/pages/users/UsersPage/UsersTable/index.jsx
> +              index={index}
Чтобы понять какая строка выбрана
`const isSelected = index === selectedRow;`

2021-06-16 11:46 UTC, andrey-dihtiarov commented on src/pages/users/UsersPage/index.jsx
> +const SKIP = 0;
Нет, мы не будем такого делать

2021-06-16 11:48 UTC, andrey-dihtiarov commented on src/pages/users/UsersPage/index.jsx
> +        <Pagination onNavigation={onNavigation} total={totalUsers} skip={SKIP} limit={LIMIT} />
Не нужно здесь передавать skip

2021-06-16 11:51 UTC, andrey-dihtiarov commented on src/store/user.js
> +export const fetchUsers = createAsyncThunk('user/fetchUsers', async ({ skip, limit, query }) => {
Для сайд-эффектов(асинхронных операций). Поэтому я не пойму, почему мы не должны здесь использовать санк?

2021-06-16 12:37 UTC, andrey-dihtiarov commented on src/utils/accountGenerator.js
> +import avatar from '../assets/mockImages/avatar.jpg';
Добавил

2021-06-16 12:40 UTC, andrey-dihtiarov commented on src/utils/accountGenerator.js
> +    birthDate: getRandomDate(new Date(1930, 1, 1), new Date(2000, 1, 1)).toISOString(),
Не, там ни первая ни вторая не использует toISOString. Это после  getRandomData я привожу к ISO string

2021-06-16 12:41 UTC, andrey-dihtiarov commented on src/pages/users/UsersPage/UsersTable/index.jsx
> +            <td>
Будет не корректное отображение таблицы. Хедеры не будут соответствовать ячейкам

2021-06-16 12:44 UTC, andrey-dihtiarov commented on src/db/UsersTable/index.js
> +    const lcQuery = query.toLowerCase();
Эта переменная здесь лишняя, я её убрал

2021-06-16 12:59 UTC, andrey-dihtiarov commented on src/components/Search/index.jsx
> +    const {
Можно

2021-06-16 13:00 UTC, andrey-dihtiarov commented on src/db/UsersTable/index.js
> +      this.db[this.table].offset(skip).limit(limit).toArray(),
Офсет и лимит нужны для пагинации. Скорее всего я просто не понял, что конкретно от меня требуется

2021-06-16 13:18 UTC, andrey-dihtiarov commented on src/db/UsersTable/index.js
> +        this.db[this.table]
Да, сделал

2021-06-16 13:22 UTC, andrey-dihtiarov commented on src/db/UsersTable/index.js
> +    if (query) {
Если будут строкой, то упадет с ошибкой. Если не передадут оба или только один, то я возвращаю всех юзеров. Т.к. Этот метот отвечает за возврат всех юзеров, с пагинацией или без. Может, в таком случае, лучше разделать на 2 метода. Где один отдает только всех юзерав, а второй какой-то лимит юзеров

2021-06-17 09:27 UTC, oleksandrbazil commented on src/components/Loader/index.jsx
> +      <div />
а зачем пустые дивы?

2021-06-17 09:27 UTC, oleksandrbazil commented on src/components/Search/index.jsx
> +      params.append('search', debouncedQuery);
тогда переименуй переменную плз

2021-06-17 09:30 UTC, oleksandrbazil commented on src/hooks/useQuery/index.js
> +const useQuery = () => new URLSearchParams(useLocation().search);
👍

2021-06-17 09:31 UTC, oleksandrbazil commented on src/pages/users/UsersPage/UsersTable/index.jsx
> +            <td>
тогда нужно исправить что бы отображалось нужное количество ячеек :)

2021-06-17 09:45 UTC, oleksandrbazil commented on src/db/UsersTable/index.js
> +        this.db[this.table]
`this.db[this.table]`
удобно так писать каждый раз?

2021-06-17 09:45 UTC, oleksandrbazil commented on src/store/user.js
> +export const fetchUsers = createAsyncThunk('user/fetchUsers', async ({ skip, limit, query }) => {
тут не особо много сайд эффектов как по мне для одной функции, по этому было непонятно, но так как используеем `@reduxjs/toolkit` то норм

2021-06-17 09:46 UTC, oleksandrbazil commented on src/utils/accountGenerator.js
> +    birthDate: getRandomDate(new Date(1930, 1, 1), new Date(2000, 1, 1)).toISOString(),
а сразу привести в функции что бы не писать дважды не хочется? :)

2021-06-17 12:07 UTC, merged