Feature/account form
andrey-dihtiarov/wizard-form-react pull request #2
Opened 2021-05-24 09:22 UTC by andrey-dihtiarov

2021-05-24 10:55 UTC, oleksandrbazil requested changes

2021-05-24 10:55 UTC, oleksandrbazil commented on src/assets/icons/eye-slash-solid.svg
> +<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="eye-slash" class="svg-inline--fa fa-eye-slash fa-w-20" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><path
Github подсвечивает ошибку  `No new line at the end of file`. Посмотри что это такое, разберись зачем это и исправь везде где она выскакивает

2021-05-24 10:55 UTC, oleksandrbazil commented on src/App.js
> +import classes from './App.module.scss';
Править не обязательно, но на будущее знай что общепринятое название для css module - styles

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/Avatar/Avatar.module.scss
> +@import "../../assets/scss/variables";
а почему решил файл назвать src/components/Avatar/Avatar.module.scss?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/Avatar/Avatar.module.scss
> +  &Placeholder {
а каким правилом руководствуешься по наименованию классов?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/Avatar/index.jsx
> +        <UserPlaceholder />
А почему выбрал путь отображать иконку как компонент? Можно ли проще написать?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/Header/Header.module.scss
> +.container {
этот класс общий или универсальный для всего приложения?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/Header/Header.module.scss
> +  &_button {
опять же таки: какой используется принцип именования классов?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/Header/Header.module.scss
> +@import '../../assets/scss/variables';
тот же вопрос что и к Avatar.module.scss

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/Header/index.jsx
> +  const onUserClick = () => history.push(`${ROUTES.newUser}${ROUTES.accountForm}`);
есть еще варианты как можно написать?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/Header/index.jsx
> +          <LinkButton icon={UserIcon} onClick={onUserClick} className={classes.nav_button}>
а почему ссылка сделана через `button` а не через `a` тэг?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/ImageUploader/ImageUploader.module.scss
> +  display: none;
а как еще можно спрятать input?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/ImageUploader/index.jsx
> +        accept=".jpg,.jpeg,.png,.svg"
с точки зрения кросс-браузерности это ненадежное решение:  https://caniuse.com/input-file-accept

Как можно это сделать по-другому?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/ImageUploader/index.jsx
> +  async function readFile(file) {
можем ли мы не использовать async?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/ImageUploader/index.jsx
> +    fileInputEl?.current.click?.();
давай договоримся что в этом задании (приложении) мы не будем использовать **safe navigation operator**

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/ImageUploader/index.jsx
> +        onChange={onFileUpload}
используешь ли какое-то правило именования хендлеров?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/buttons/FlatButton/index.jsx
> +const FlatButton = ({ type, option, children, ...props }) => (
как правило ...props => ...rest

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/buttons/FlatButton/index.jsx
> +  <button type={type} className={`${classes.button} ${classes[option]}`} {...props}>
1) зачем нам вытягивать параметр `type`?
2) какую суть отображает параметр option? как еще можно назвать этот параметр?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/buttons/IconButton/index.jsx
> +  <button className={`${classes.button} ${className}`} {...props}>
можно ли написать немного короче?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/buttons/IconButton/index.jsx
> +const IconButton = ({ children, className, ...props }) => (
как по мне, этот компонент пустой.... можем ли мы переиспользовать `LinkButton`?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/buttons/LinkButton/index.jsx
> +  <button type={type} className={`${classes.button} ${className}`} {...props}>
мне кажется или `classes.button` не существует?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/buttons/LinkButton/index.jsx
> +const LinkButton = ({ icon: Icon, className, type, children, ...props }) => (
этот компонент как-то очень похож на `FlatButton`, тебе так не кажется?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/icons/index.js
> +export const UsersIcon = (props) => <Icon icon={UserFriendsSolid} {...props} />;
тебе не кажется что этот код лишний и с ним нужно что-то сделать?
Есть какие-то идеи?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/icons/index.js
> +  <Component width={width} height={height} fill={fill} {...props} />
а как еще можно задать передать базовые параметры без деструктуризации входящих параметров?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/inputs/InputContainer/index.jsx
> +InputContainer.propTypes = {
почему не все параметры описаны?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/inputs/InputContainer/index.jsx
> +      <ErrorMessage name={name}>{(msg) => msg}</ErrorMessage>
а что это за магия с переменной `msg`?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/inputs/PasswordInput/PasswordInput.module.scss
> +  &:focus {
какие есть еще состояния?

2021-05-24 10:55 UTC, oleksandrbazil commented on src/components/inputs/PasswordInput/index.jsx
> +  label: PropTypes.string,
не все параметры объявлены, пожалуйста, проверь все компоненты, вдруг где еще упустил

2021-05-24 10:55 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/index.jsx
> +const validationSchema = Yup.object().shape({
предполагаю что после добавления второй формы, у нас не получится отправить первую форму, так как валидация будет работать на все формы сразу.
+ выглядит не логичным отделение валидации полей Аккаунт формы от самих полей

Так что, мое мнение таково: 
форма и валидация должна быть в одном месте что бы редактируюя одно (инпуты) не забыть обновить другое (валидацию)

2021-05-24 12:43 UTC, andrey-dihtiarov commented on src/assets/icons/eye-slash-solid.svg
> +<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="eye-slash" class="svg-inline--fa fa-eye-slash fa-w-20" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><path
Исправил

2021-05-24 12:43 UTC, andrey-dihtiarov commented on src/App.js
> +import classes from './App.module.scss';
Исправил

2021-05-24 12:43 UTC, andrey-dihtiarov commented on src/components/Avatar/Avatar.module.scss
> +@import "../../assets/scss/variables";
Называю модули стилей именем самого компонента. Т.е. для "Header" компонента будет "Header.module.scss", для "Avatar" будет "Avatar.module.scss" и т.д. Может я не правильно понял вопрос, тогда уточни еще раз пожалуйста, что именно ты имел в виду.

2021-05-24 12:43 UTC, andrey-dihtiarov commented on src/components/Avatar/Avatar.module.scss
> +  &Placeholder {
Решил использовать "camelCase" т.к. пришлось бы писать что-то вроде styles['avatar-placeholder'] если бы использовал обычный нейминг классов и плюс авто-комплит не работает. А так, пишешь styles.avatarPlaceholder и быстрее, и авто-комплит хорошо работает. Можно еще "snake_case" было использовать styles.avatar_placeholder. Тоже авто-комплит хорошо работает. Но мне показалось, что в "camelCase" стиле ближе к джаваскрипту и решил использовать именно такой нейминг. Читал за "camelCase" в "css modules" и, вроде как, за плохую практику не считается, люди используют.

2021-05-24 12:44 UTC, andrey-dihtiarov commented on src/components/Avatar/index.jsx
> +        <UserPlaceholder />
Если делаю иконку как компонент, то она реагирует на изменение цвета. Я не хотел хардкодить цвет в СВГшке, а менять динамически.

2021-05-24 13:06 UTC, andrey-dihtiarov commented on src/components/Header/Header.module.scss
> +.container {
Не совсем понял вопрос. Этот класс используется только для компонента "Header".

2021-05-24 13:08 UTC, andrey-dihtiarov commented on src/components/Header/Header.module.scss
> +  &_button {
Я ошибся. Поправил на camelCase.

2021-05-24 13:09 UTC, andrey-dihtiarov commented on src/components/Header/Header.module.scss
> +@import '../../assets/scss/variables';
Модуль стилей называю так же, как и компонент.

2021-05-24 13:11 UTC, andrey-dihtiarov commented on src/components/Header/index.jsx
> +  const onUserClick = () => history.push(`${ROUTES.newUser}${ROUTES.accountForm}`);
`const onUserClick = () => history.push(ROUTES.newUser + ROUTES.accountForm);`

2021-05-24 13:22 UTC, andrey-dihtiarov commented on src/components/Header/index.jsx
> +          <LinkButton icon={UserIcon} onClick={onUserClick} className={classes.nav_button}>
My bad. Поправил.

2021-05-24 13:25 UTC, andrey-dihtiarov commented on src/components/ImageUploader/ImageUploader.module.scss
> +  display: none;
Указать тип "hidden", но мне нужен же тип "file". В css: opacity: 0, visibility: hidden.

2021-05-24 13:26 UTC, andrey-dihtiarov commented on src/components/ImageUploader/index.jsx
> +        accept=".jpg,.jpeg,.png,.svg"
Сделать формик валидацию на тип файла.

2021-05-24 14:18 UTC, andrey-dihtiarov commented on src/components/ImageUploader/index.jsx
> +  async function readFile(file) {
Да, вместо `reader.onload` использовать `reader.onloadend`.

2021-05-24 14:22 UTC, andrey-dihtiarov commented on src/components/ImageUploader/index.jsx
> +    fileInputEl?.current.click?.();
Хорошо. Убрал.

2021-05-24 14:24 UTC, andrey-dihtiarov commented on src/components/ImageUploader/index.jsx
> +        onChange={onFileUpload}
Просто пишу: onButtonClick, onInputChange и т.д. Нужно что-то вроде handleInputChange, handleButtonClick?

2021-05-24 14:25 UTC, andrey-dihtiarov commented on src/components/buttons/FlatButton/index.jsx
> +const FlatButton = ({ type, option, children, ...props }) => (
Я еще ...others писал. Поправить везде на ...rest?

2021-05-24 14:31 UTC, andrey-dihtiarov commented on src/components/buttons/FlatButton/index.jsx
> +  <button type={type} className={`${classes.button} ${classes[option]}`} {...props}>
1) Да, действительно. Упустил этот момент. Оно же все равно через ...props зайдет. 
2) Variation, variant, version. не знаю даже как еще.

2021-05-24 14:35 UTC, andrey-dihtiarov commented on src/components/buttons/IconButton/index.jsx
> +  <button className={`${classes.button} ${className}`} {...props}>
Тут я не совсем понял, что именно короче нужно сделать.
Я подумал про:
``${classes.button} ${className}``
можно поменять на:
``${button} ${className}``

2021-05-24 14:56 UTC, andrey-dihtiarov commented on src/components/buttons/IconButton/index.jsx
> +const IconButton = ({ children, className, ...props }) => (
Да, согласен.

2021-05-24 14:57 UTC, andrey-dihtiarov commented on src/components/buttons/LinkButton/index.jsx
> +  <button type={type} className={`${classes.button} ${className}`} {...props}>
Не, все есть.

2021-05-24 14:58 UTC, andrey-dihtiarov commented on src/components/buttons/LinkButton/index.jsx
> +const LinkButton = ({ icon: Icon, className, type, children, ...props }) => (
Уже изменил его. Теперь это линка а не баттон. Так как ты писал про навигацию, а в навигации должна быть ссылка.

2021-05-24 15:01 UTC, andrey-dihtiarov commented on src/components/icons/index.js
> +export const UsersIcon = (props) => <Icon icon={UserFriendsSolid} {...props} />;
Наверное лишний. Можно просто ипортировать вот так `import { ReactComponent as UserFriendsSolid } from '../../assets/icons/user-friends-solid.svg';` и сразу нормально использовать иконку

2021-05-24 15:04 UTC, andrey-dihtiarov commented on src/components/icons/index.js
> +  <Component width={width} height={height} fill={fill} {...props} />
Возможно не совсем понял вопрос. Так что не знаю. Если можешь, напиши пример плиз, как это должно выглядеть

2021-05-24 15:07 UTC, andrey-dihtiarov commented on src/components/inputs/InputContainer/index.jsx
> +InputContainer.propTypes = {
Там некоторые пропсы приходят из "Field" компонента формика. Там просто очень много описывать что лежит в "field" и "form" пропсах. Можно, конечно, их описать просто как объект.

2021-05-24 15:12 UTC, andrey-dihtiarov commented on src/components/inputs/InputContainer/index.jsx
> +      <ErrorMessage name={name}>{(msg) => msg}</ErrorMessage>
![image](https://user-images.githubusercontent.com/82100556/119368042-42c44f80-bcbb-11eb-8422-1943d6fb7e51.png)
Это компонент формика, который отрендерит ошибку, если она есть, конечно же.
https://formik.org/docs/api/errormessage

2021-05-24 15:19 UTC, andrey-dihtiarov commented on src/components/inputs/PasswordInput/PasswordInput.module.scss
> +  &:focus {
Про какие состояния речь? Про :active, :visited и т.д? Конкретно для инпутов больше не знаю. Гугл говорит про ":focus-visible и :focus-within"

2021-05-24 15:20 UTC, andrey-dihtiarov commented on src/components/inputs/PasswordInput/index.jsx
> +  label: PropTypes.string,
(Та же ситуация, что и с InputContainer) Там некоторые пропсы приходят из "Field" компонента формика. Там просто очень много описывать что лежит в "field" и "form" пропсах. Можно, конечно, их описать просто как объект.

2021-05-24 15:29 UTC, andrey-dihtiarov commented on src/pages/users/UserFormPage/index.jsx
> +const validationSchema = Yup.object().shape({
Нам же, вроде бы, нужно сабмитить форму только на последнем шаге. А до этого(допустим, на первой форме) мы просто будем валидировать поля по нажатию кнопки, и если есть ошибки, то не пускать юзера заполнять форму дальше. Т.е. никакого сабмита формы на 1м, 2м и 3м шаге не должно быть.
![image](https://user-images.githubusercontent.com/82100556/119370292-caab5900-bcbd-11eb-8c87-6bbd01a60313.png)
![image](https://user-images.githubusercontent.com/82100556/119370354-db5bcf00-bcbd-11eb-9a4a-037424131958.png)

2021-05-24 15:37 UTC, oleksandrbazil commented on src/components/Avatar/Avatar.module.scss
> +@import "../../assets/scss/variables";
та не, все ты правильно понял, просто не вижу смысла давать названия, ты же используешь паттерн 
`src/components/Header/index.jsx`

Почему нельзя такой же использовать для стилей?

2021-05-24 15:38 UTC, oleksandrbazil commented on src/components/Avatar/Avatar.module.scss
> +  &Placeholder {
ок, тогда убедись что все css modules написаны в этом стиле, и придумай как давать название Модификаторам

2021-05-24 15:45 UTC, oleksandrbazil commented on src/components/Header/Header.module.scss
> +.container {
в моей картине мира класс `.container` это глобальный класс для построения структуры в [Bootstrap](https://getbootstrap.com/docs/5.0/layout/containers/), [Bulma](https://bulma.io/documentation/layout/container/), [TailWind](https://tailwindcss.com/docs/container) 
по этому я бы выбрал другое название:
- header_inner - если внутренний контейнер
- header_wrapper - если внешний контейнер

2021-05-24 15:45 UTC, oleksandrbazil commented on src/components/Header/Header.module.scss
> +@import '../../assets/scss/variables';
закрываю комментарий в пользу треда https://github.com/andrey-dihtiarov/wizard-form-react/pull/2#discussion_r638059377

2021-05-24 15:47 UTC, oleksandrbazil commented on src/components/ImageUploader/ImageUploader.module.scss
> +  display: none;
в чем будет разница между `display: none ` vs  `opacity: 0, visibility: hidden.`?

2021-05-24 15:47 UTC, oleksandrbazil commented on src/components/ImageUploader/index.jsx
> +        accept=".jpg,.jpeg,.png,.svg"
если не успеешь сделать и нужно мерджить - добавь хотя бы TODO коммент

2021-05-24 15:48 UTC, oleksandrbazil commented on src/components/ImageUploader/index.jsx
> +  async function readFile(file) {
допустим, а в других местах?

2021-05-24 15:48 UTC, oleksandrbazil commented on src/components/ImageUploader/index.jsx
> +        onChange={onFileUpload}
в целом да, но если из более одного тогда нужно дать уникальное имя

2021-05-24 15:49 UTC, oleksandrbazil commented on src/components/ImageUploader/index.jsx
> +        onChange={onFileUpload}
мне показалось что в данном случае уместно дать имя `onFileChange` но в целом ответ годен :)

2021-05-24 15:50 UTC, oleksandrbazil commented on src/components/buttons/FlatButton/index.jsx
> +  <button type={type} className={`${classes.button} ${classes[option]}`} {...props}>
- variant, kind 👍 
- version  👎

2021-05-24 15:51 UTC, oleksandrbazil commented on src/components/buttons/LinkButton/index.jsx
> +  <button type={type} className={`${classes.button} ${className}`} {...props}>
ну ок :)

2021-05-24 15:52 UTC, oleksandrbazil commented on src/components/icons/index.js
> +export const UsersIcon = (props) => <Icon icon={UserFriendsSolid} {...props} />;
как насчет того что бы создать компонент в который можно передать только название иконки?

2021-05-24 15:53 UTC, oleksandrbazil commented on src/components/icons/index.js
> +  <Component width={width} height={height} fill={fill} {...props} />
попробуй занести базовые параметры в переменную...

2021-05-24 15:54 UTC, oleksandrbazil commented on src/components/inputs/InputContainer/index.jsx
> +InputContainer.propTypes = {
а можно ли описать объект частично?

2021-05-24 15:54 UTC, oleksandrbazil commented on src/components/inputs/InputContainer/index.jsx
> +      <ErrorMessage name={name}>{(msg) => msg}</ErrorMessage>
тогда было бы лучше передать параметром, что бы явно увидеть

2021-05-24 15:58 UTC, oleksandrbazil commented on src/components/inputs/PasswordInput/PasswordInput.module.scss
> +  &:focus {
кое-что упустил, почитай http://htmlbook.ru/samcss/psevdoklassy

2021-05-24 15:59 UTC, oleksandrbazil commented on src/components/inputs/PasswordInput/index.jsx
> +  label: PropTypes.string,
закрываю комменты в пользу https://github.com/andrey-dihtiarov/wizard-form-react/pull/2#discussion_r638071430

2021-05-24 16:00 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/index.jsx
> +const validationSchema = Yup.object().shape({
похоже понимание должно появиться после реализации второй формы, по этому пока что закрою этот тред комментариев

2021-05-24 16:05 UTC, oleksandrbazil requested changes
Посмотри на те комментарии что еще не скрыты, и ответь на них пожалуйста
Если с чем-то согласен, то запуш изменения и жди request review

2021-05-24 16:05 UTC, oleksandrbazil commented on src/components/Avatar/index.jsx
> +        <UserPlaceholder />
ок, убедил, оставляем так как есть (пока что) :)

2021-05-25 06:59 UTC, andrey-dihtiarov commented on src/components/ImageUploader/ImageUploader.module.scss
> +  display: none;
display: none убирает элемент из потока страницы, а opacity и visibility: hidden просто делают элемент невидимым.

2021-05-25 07:23 UTC, andrey-dihtiarov commented on src/components/ImageUploader/index.jsx
> +  async function readFile(file) {
Имеется в виду, что вместо async/await можно использовать? Если да, то можно использовать `.then()`.
В итоге получится так:
![image](https://user-images.githubusercontent.com/82100556/119456319-3d124c80-bd43-11eb-9642-c47cfc101784.png)

2021-05-25 07:35 UTC, andrey-dihtiarov commented on src/components/ImageUploader/index.jsx
> +        onChange={onFileUpload}
Переименовал

2021-05-25 07:50 UTC, andrey-dihtiarov commented on src/components/buttons/FlatButton/index.jsx
> +  <button type={type} className={`${classes.button} ${classes[option]}`} {...props}>
Поменял на variant

2021-05-25 08:39 UTC, andrey-dihtiarov commented on src/components/icons/index.js
> +export const UsersIcon = (props) => <Icon icon={UserFriendsSolid} {...props} />;
Переделал

2021-05-25 08:40 UTC, andrey-dihtiarov commented on src/components/icons/index.js
> +  <Component width={width} height={height} fill={fill} {...props} />
![image](https://user-images.githubusercontent.com/82100556/119467158-f1b16b80-bd4d-11eb-848f-d8b5a8e6ddd3.png)
Все равно не совсем понял. Имеется в виду сделать вот так?
![image](https://user-images.githubusercontent.com/82100556/119467233-fece5a80-bd4d-11eb-95f7-8b402ccc6f48.png)

2021-05-25 08:49 UTC, andrey-dihtiarov commented on src/components/Header/Header.module.scss
> +.container {
Переименовал

2021-05-25 09:50 UTC, andrey-dihtiarov commented on src/components/inputs/InputContainer/index.jsx
> +InputContainer.propTypes = {
Добавил новые проп-тайпс.

2021-05-25 09:51 UTC, andrey-dihtiarov commented on src/components/ImageUploader/index.jsx
> +        accept=".jpg,.jpeg,.png,.svg"
Хорошо

2021-05-25 09:51 UTC, andrey-dihtiarov commented on src/components/Avatar/Avatar.module.scss
> +  &Placeholder {
Перепроверил

2021-05-25 10:03 UTC, andrey-dihtiarov commented on src/components/Avatar/Avatar.module.scss
> +@import "../../assets/scss/variables";
![image](https://user-images.githubusercontent.com/82100556/119478733-b9635a80-bd58-11eb-8164-eb6c9608a1fd.png)
Мне нравится, что когда называешь именем компонента, то сразу в инспекторе видно откуда эти стили.

Переименовал все в `styles.module.scss`

2021-05-25 10:04 UTC, andrey-dihtiarov commented on src/components/inputs/PasswordInput/PasswordInput.module.scss
> +  &:focus {
Хорошо

2021-05-25 11:17 UTC, oleksandrbazil commented on src/components/icons/index.js
> +  <Component width={width} height={height} fill={fill} {...props} />
Хотел увидеть что знаешь как подмешивать поля
```js
const props = {width: 16, height: 16, fill: '#C2CFDF', ...rest};
```

2021-05-25 11:18 UTC, oleksandrbazil approved these changes

2021-05-25 11:21 UTC, merged