Feature/profile account
andrey-dihtiarov/wizard-form-react pull request #3
Opened 2021-05-26 11:04 UTC by andrey-dihtiarov

Добавил все нужные компоненты для profile формы (DateInput, RadioGroup и AddressInput). Но не добавлял все поля в профайл форму пока, т.к. решили, что нужно быстрее браться за step wizzard компонент.

2021-05-26 11:29 UTC, oleksandrbazil requested changes

2021-05-26 11:29 UTC, oleksandrbazil commented on src/components/RadioGroup/index.jsx
> +      <div className={styles.radioGroup} onChange={onValueChange}>
а как onChange handler обрабатывается? это по документации так?
мне кажется тут что-то не так

2021-05-26 11:29 UTC, oleksandrbazil commented on src/components/RadioGroup/index.jsx
> +        {values &&
нет смысла проверять есть ли values что бы отмаппить его

2021-05-26 11:29 UTC, oleksandrbazil commented on src/components/RadioGroup/index.jsx
> +const RadioGroup = ({ values, name }) => {
значение по умолчанию?

2021-05-26 11:29 UTC, oleksandrbazil commented on src/components/forms/ProfileForm/index.jsx
> +const GenderRadioGroupValues = ['Male', 'Female'];
есть ли реальный смысл тут выносить это в константу?

2021-05-26 11:29 UTC, oleksandrbazil commented on src/components/inputs/AddressInput/index.jsx
> +        placeholder="Where are we going?"
похоже как будь-то забыли убрать placeholder после копи-паста примера

2021-05-26 11:29 UTC, oleksandrbazil commented on src/components/inputs/AddressInput/index.jsx
> +        className={`${styles.field} ${isError && styles.fieldError}`}
в данном случае лучше писать тернарным оператором что бы не было слова undefined в классах
Проверь плз и другие компоненты

2021-05-26 11:29 UTC, oleksandrbazil commented on src/components/inputs/RadioInput/index.jsx
> +const RadioInput = ({ field: { name, value }, label, className, checked, ...rest }) => (
а нам точно нужно выносить в отдельный компонент?

2021-05-26 11:29 UTC, oleksandrbazil commented on src/components/inputs/RadioInput/index.jsx
> +export default RadioInput;
не описаны пропсы

2021-05-26 11:29 UTC, oleksandrbazil commented on src/index.scss
> +@import '~react-datepicker/dist/react-datepicker.css';
почему решил импортировать стили тут?

2021-05-26 11:29 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/index.jsx
> +  birthDate: Yup.date().max(subYears(Date.now(), 18), 'User must be older 18').required('Required'),
а зачем добавил эту библиотеку? думаю в тех задании не говорилось о ней

```*T ```

2021-05-26 11:29 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/index.jsx
> +  gender: Yup.string().oneOf(['Male', 'Female']).required('Required'),
я ранее писал зачем выносил в константы (не использовались), теперь вижу что нужно выносить и переиспользовать тут
кроме этого сделай так что бы константы нельзя было изменить в runtime

2021-05-30 12:45 UTC, andrey-dihtiarov commented on src/components/RadioGroup/index.jsx
> +      <div className={styles.radioGroup} onChange={onValueChange}>
Исправил

2021-05-30 12:46 UTC, andrey-dihtiarov commented on src/components/RadioGroup/index.jsx
> +        {values &&
Точно. Убрал это

2021-05-30 12:50 UTC, andrey-dihtiarov commented on src/components/inputs/AddressInput/index.jsx
> +        placeholder="Where are we going?"
Убрал

2021-05-30 12:56 UTC, andrey-dihtiarov commented on src/components/forms/ProfileForm/index.jsx
> +const GenderRadioGroupValues = ['Male', 'Female'];
Убрал константу

2021-05-30 13:03 UTC, andrey-dihtiarov commented on src/components/inputs/AddressInput/index.jsx
> +        className={`${styles.field} ${isError && styles.fieldError}`}
Да, спасибо. Не обратил на это внимание. Поправил

2021-05-30 13:05 UTC, andrey-dihtiarov commented on src/components/inputs/RadioInput/index.jsx
> +export default RadioInput;
Убрал этот компонент т.к. он оказался излишним

2021-05-30 13:07 UTC, andrey-dihtiarov commented on src/index.scss
> +@import '~react-datepicker/dist/react-datepicker.css';
Хотелось бы все стили, которые не модули, имрортировать куда-то в одно место. Если нужно, то поправлю

2021-05-30 13:08 UTC, andrey-dihtiarov commented on src/pages/users/UserFormPage/index.jsx
> +  birthDate: Yup.date().max(subYears(Date.now(), 18), 'User must be older 18').required('Required'),
Речь про date-fns? Библиотеки для работы со временем нельзя использовать?

2021-05-30 13:30 UTC, andrey-dihtiarov commented on src/pages/users/UserFormPage/index.jsx
> +  gender: Yup.string().oneOf(['Male', 'Female']).required('Required'),
Сделал

2021-05-30 13:31 UTC, andrey-dihtiarov commented on src/components/inputs/RadioInput/index.jsx
> +const RadioInput = ({ field: { name, value }, label, className, checked, ...rest }) => (
Убрал этот компонент

2021-05-30 13:32 UTC, andrey-dihtiarov commented on src/components/RadioGroup/index.jsx
> +const RadioGroup = ({ values, name }) => {
Не понял о чем речь. Уточни плиз

2021-05-31 15:04 UTC, oleksandrbazil approved these changes

2021-05-31 15:07 UTC, merged