Feature/step wizard
andrey-dihtiarov/wizard-form-react pull request #4
Opened 2021-05-31 06:40 UTC by andrey-dihtiarov

2021-05-31 16:42 UTC, oleksandrbazil requested changes

2021-05-31 16:42 UTC, oleksandrbazil commented on src/components/StepWizard/Wizard/index.jsx
> +const Wizard = ({ steps, onForward, onBack, onFinish }) => {
перенеси в index.js

2021-05-31 16:42 UTC, oleksandrbazil commented on src/components/StepWizard/Wizard/index.jsx
> +        <Step {...props}>
убрать Step компонент, потому  что он не не сет никакой нагрузки

2021-05-31 16:42 UTC, oleksandrbazil commented on src/components/StepWizard/Step/index.jsx
> +  const mappedChildren = React.Children.map(children, (child) =>
попробуй без таких конструкций, можно написать проще, я верю :)

2021-05-31 16:42 UTC, oleksandrbazil commented on src/components/StepWizard/Wizard/index.jsx
> +  useEffect(() => {
скинь плз ссылку

2021-05-31 16:42 UTC, oleksandrbazil commented on src/components/StepWizard/WizardHeader/index.jsx
> +    variant = isDisabled ? 'disabled' : variant;
перепиши что бы было читабильней

2021-05-31 16:42 UTC, oleksandrbazil commented on src/components/StepWizard/WizardHeader/index.jsx
> +          <Link className={styles.link} key={step.slug} to={path.replace(':slug', step.slug)}>
деструктуризация

2021-05-31 16:42 UTC, oleksandrbazil commented on src/components/StepWizard/WizardHeader/index.jsx
> +            <FlatButton disabled={isDisabled} className={`${styles.button} ${styles[variant]}`}>
посмотри будет ли проще если написать 1-м компопентом ссылку и кнопку

2021-05-31 16:42 UTC, oleksandrbazil commented on src/components/buttons/FlatButton/index.jsx
> +const ButtonOptions = ['primary', 'cancel', 'success', 'disabled'];
убери плз disabled

2021-05-31 16:42 UTC, oleksandrbazil commented on src/components/buttons/FlatButton/index.jsx
> +const ButtonOptions = ['primary', 'cancel', 'success', 'disabled'];
options переименуй плз

2021-05-31 16:42 UTC, oleksandrbazil commented on src/components/buttons/LinkButton/index.jsx
> +  <NavLink to={to} className={`${styles.button} ${className}`} {...props}>
...rest

2021-05-31 16:42 UTC, oleksandrbazil commented on src/components/forms/AccountForm/index.jsx
> +const FILE_SIZE = 1024 * 1024;
в чем измеряем?

2021-05-31 16:42 UTC, oleksandrbazil commented on src/components/forms/AccountForm/index.jsx
> +    .test('fileSize', 'File too large', (value) => (value ? value.size <= FILE_SIZE : true))
деструктуризация

2021-05-31 16:42 UTC, oleksandrbazil commented on src/components/forms/CapabilitiesForm/index.jsx
> +// import FormikForm from '../../FormikForm';
комменты старайся удалять

2021-05-31 16:42 UTC, oleksandrbazil commented on src/constants/index.js
> +  //form slugs
зачем оно тут? обязательно ли?

2021-05-31 16:42 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/index.jsx
> +import Wizard from '../../../components/StepWizard/Wizard';
перенеси формы поближе, плз

2021-05-31 16:42 UTC, oleksandrbazil commented on src/store/user.js
> +  initialState: INIT_STATE,
зачем константа?

2021-06-01 15:37 UTC, oleksandrbazil requested changes

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/NavButtons/index.jsx
> +const NavButtons = ({ isFirst, isLast, onBack }) => {
как думаешь будет ли где-то использоваться этот компонент кроме StepWizard компонента?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/NavButtons/index.jsx
> +    <FlatButton type="submit" variant="success">
какой тип по умолчанию будет в браузере у кнопки?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/Header/index.jsx
> +          to={`${ROUTES.newUser.replace(':slug', 'account')}`}
название slug не вписывается в newUser path, и почему мы делаем ссылку на AccountForm? 
Что будет если поменять формы местами (Account <=> Profile) и нужно ли будет потом менять тут ссылку?
.....

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/FormikForm/index.jsx
> +const FormikForm = ({ initialValues, validationSchema, submit, children, className }) => (
Выглядит как пустой компонент....
Какую логику он хранит? зачем нам отдельный компонент?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/NavButtons/index.jsx
> +    <FlatButton type="button" variant="cancel" onClick={onBack}>
а если расширить `FlatButton` на прием параметра `title || name` то количество строк в этом компоненте можно уменьшить и код будет смотреться лаконичней

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/NavButtons/index.jsx
> +      {backButton}
Попробуй переписать что бы компонент соответствовал: 
```
const Component = () => {
  // логика находиться тут
  return (
     //отображение тут
  )
}
```

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardHeader/index.jsx
> +            {`${index + 1}. ${title}`}
а зачем все оборачивать в {} ?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardHeader/index.jsx
> +      {steps.map((step, index) => {
а не проще было бы передать готовый массив данных и не выносить логику в Header компонент?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardHeader/styles.module.scss
> +@import '../../../assets/scss/variables';
зачем они нам?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardTab/index.jsx
> +  children: 'Tab',
зачем нам такое значение?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/StepWizard/index.jsx
> +      history.push(path.replace(':slug', slugs[currentSlugIndex + 1]));
зачем писать  `currentSlugIndex + 1` дважды?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/StepWizard/index.jsx
> +  const defaultSlug = steps[0].slug;
Что произойдет если slugs передать как пустой массив?
Как можно безопасно взять слаг первого элемента в массиве?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/StepWizard/index.jsx
> +  const currentSlugIndex = useMemo(() => slugs.findIndex((item) => item === slug), [slug, slugs]);
можно обойтись без этой переменной?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/StepWizard/index.jsx
> +  const mappedSteps = useMemo(() => {
перенеси в блок рендера, пожалуйста

2021-06-01 15:37 UTC, oleksandrbazil commented on src/components/buttons/FlatButton/index.jsx
> +  variant: '',
а почему можно сделать кнопку без варианта?
может нужно добавить тогда default?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/constants/index.js
> +  newUser: '/users/new/:slug',
а что мы будем писать когда StepWizzard нужен будет на какой-то другой странице?
например: /newAdminUser ?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/AccountForm/index.jsx
> +const ONE_MEGABYTE = 1024 * 1024;
MAX_IMAGE_SIZE: ...// 1Mb

2021-06-01 15:37 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/AccountForm/index.jsx
> +        const { size } = value;
а безопасно деструктуризировать невозможно?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/AccountForm/styles.module.scss
> +  & > * {
почему решил написать стили таким образом? на кого повлияют эти стили?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/ProfileForm/index.jsx
> +  const initValues = { firstName, lastName, email, birthDate, gender, address };
зачем дважды деструктуризировать?

2021-06-01 15:37 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/ProfileForm/styles.module.scss
> +  & > * {
где-то я уже это видел (/src/pages/users/UserFormPage/AccountForm/styles.module.scss:35)
Зачем нам нужно повторять такой трюк?

2021-06-02 07:29 UTC, andrey-dihtiarov commented on src/components/FormikForm/index.jsx
> +const FormikForm = ({ initialValues, validationSchema, submit, children, className }) => (
Просто решил как обертку сделать, чтобы <Form></Form> не писать. Да, он реально не нужен. Убрал

2021-06-02 07:32 UTC, andrey-dihtiarov commented on src/components/Header/index.jsx
> +          to={`${ROUTES.newUser.replace(':slug', 'account')}`}
Да, нужно будет поменять ссылку. А на счет "slug", почему не подходит? Можно на "step" поменять, если что. "step", наверное, больше будет подходить.

2021-06-02 07:36 UTC, andrey-dihtiarov commented on src/components/NavButtons/index.jsx
> +const NavButtons = ({ isFirst, isLast, onBack }) => {
Он будет использоваться во всех формах. Больше нигде.

2021-06-02 07:39 UTC, andrey-dihtiarov commented on src/components/NavButtons/index.jsx
> +    <FlatButton type="button" variant="cancel" onClick={onBack}>
Речь про то, чтобы заменить использование "children" на "name || title" пропс?

2021-06-02 07:39 UTC, andrey-dihtiarov commented on src/components/NavButtons/index.jsx
> +    <FlatButton type="submit" variant="success">
Сабмит

2021-06-02 07:54 UTC, andrey-dihtiarov commented on src/components/StepWizard/StepWizardHeader/index.jsx
> +            {`${index + 1}. ${title}`}
Будет вот так, если не обернуть:
![image](https://user-images.githubusercontent.com/82100556/120444336-35305900-c390-11eb-8926-dccd618859ee.png)
Можно просто вынести в переменную, допустим, tabTitle:
![image](https://user-images.githubusercontent.com/82100556/120444625-77599a80-c390-11eb-8c9f-a1a80c7e832b.png)
![image](https://user-images.githubusercontent.com/82100556/120445010-de774f00-c390-11eb-9711-8a36ddfd0e30.png)

А можно не передавать как "children", а добавить "title" в "StepWizardHeader

2021-06-02 07:58 UTC, andrey-dihtiarov commented on src/components/StepWizard/StepWizardHeader/styles.module.scss
> +@import '../../../assets/scss/variables';
Я храню в переменных цвета. Так проще для меня лично. Очень много где цвета переиспользуются и я решил их вынести в константы.

2021-06-02 08:03 UTC, andrey-dihtiarov commented on src/components/StepWizard/StepWizardTab/index.jsx
> +  children: 'Tab',
Это заголовок табы по умолчанию. Для "FlatButton" у меня тоже есть такое значение - 'FlatButton'. Мне просто пустую строку оставить? Или сделать чтобы "children", которые выступают тут как "title" сделать обязательными? Т.е: `children: PropTypes.string.isRequired`

2021-06-02 08:13 UTC, andrey-dihtiarov commented on src/components/StepWizard/index.jsx
> +  const defaultSlug = steps[0].slug;
1. Приложение упадет с ошибкой.
2. Можно сделать вот так:
![image](https://user-images.githubusercontent.com/82100556/120447749-91e14300-c393-11eb-8f98-926a9be37dc2.png)

2021-06-02 09:42 UTC, andrey-dihtiarov commented on src/constants/index.js
> +  newUser: '/users/new/:slug',
Мысль понял. Обернул StepWizard в hoc, уже hoc будет добавлять `/:slug` параметр

2021-06-02 09:44 UTC, andrey-dihtiarov commented on src/pages/users/UserFormPage/AccountForm/index.jsx
> +        const { size } = value;
` .test('fileSize', 'File too large', (value) => ({ size }) => size ? size < ONE_MEGABYTE : true)`
Т.е вот так вот сделать? Если да, то не получается так

2021-06-02 09:56 UTC, andrey-dihtiarov commented on src/pages/users/UserFormPage/AccountForm/styles.module.scss
> +  & > * {
![image](https://user-images.githubusercontent.com/82100556/120459184-9fe99080-c3a0-11eb-8488-05c7ba9bdd4c.png)
Чтобы был маржин между кнопками. Можно, конечно, просто контейнеру кнопок поставить фиксированную ширину и `justify-content: space-between` сделать. Но тогда для контейнера еще один контейнер нужен будет, чтобы выровнять этот контейнер.

2021-06-02 10:18 UTC, andrey-dihtiarov commented on src/pages/users/UserFormPage/ProfileForm/index.jsx
> +  const initValues = { firstName, lastName, email, birthDate, gender, address };
Не вижу где 2я деструктуризация. 2й раз я просто записал все вытянутые значения в переменную `initValues` чтобы передать их формику

2021-06-02 10:24 UTC, andrey-dihtiarov commented on src/pages/users/UserFormPage/ProfileForm/styles.module.scss
> +  & > * {
Можно не повторять. Можно прям в компоненте NavButton обернуть кнопки в контейнер и сделать `& > * ` один раз. Можно отдельно на 1ну кнопку повесить маржин. А можно, как я уже писал выше, просто использовать фиксированную ширину для контейнера. Но тогда нужен будет еще один контейнер. Еще можно использовать `gap`, но у этого свойства только 72% покрытия всех браузеров, хоть во всех новых уже и работает

2021-06-02 10:32 UTC, andrey-dihtiarov commented on src/components/buttons/FlatButton/index.jsx
> +  variant: '',
Делал это для визард табов. Точно не помню зачем. Убрал это

2021-06-02 10:33 UTC, andrey-dihtiarov commented on src/components/StepWizard/index.jsx
> +  const currentSlugIndex = useMemo(() => slugs.findIndex((item) => item === slug), [slug, slugs]);
Да, можно. "activeStep"  переменная выполняет ту же функцию. Убрал "currentSlugIndex.

2021-06-02 10:33 UTC, andrey-dihtiarov commented on src/components/StepWizard/index.jsx
> +      history.push(path.replace(':slug', slugs[currentSlugIndex + 1]));
Точно, убрал это. И убрал "steps" переменную, она лишняя как и "currentSlugIndex" переменная

2021-06-02 10:55 UTC, andrey-dihtiarov commented on src/components/StepWizard/StepWizardHeader/index.jsx
> +      {steps.map((step, index) => {
Кода будет меньше. Вынес всю логику выше, в StepWizard компонент

2021-06-03 09:46 UTC, oleksandrbazil commented on src/components/NavButtons/index.jsx
> +const NavButtons = ({ isFirst, isLast, onBack }) => {
я тебя толкаю к мысли что эти кнопки относятся к степвизарду и лежать должны в другом месте

2021-06-03 09:47 UTC, oleksandrbazil commented on src/components/NavButtons/index.jsx
> +    <FlatButton type="submit" variant="success">
тогда зачем нам явно передавать этот параметр?

2021-06-03 09:49 UTC, oleksandrbazil commented on src/components/NavButtons/index.jsx
> +    <FlatButton type="button" variant="cancel" onClick={onBack}>
зачем заменять? ты же можешь настроить компонент так что бы отображать title или children?

2021-06-03 09:52 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardTab/index.jsx
> +  children: 'Tab',
уж лучше пустую стоку

2021-06-03 09:59 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/AccountForm/index.jsx
> +        const { size } = value;
почему? может потому что скобки забыл добавить?

2021-06-03 10:05 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/AccountForm/styles.module.scss
> +  & > * {
я бы постарался написать стили по другому...

2021-06-03 10:18 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/ProfileForm/index.jsx
> +  const initValues = { firstName, lastName, email, birthDate, gender, address };
согласен, нет второй дестуктуризации, меня смутило наличие этого кода, сейчас я склоняюсь к тому что нет смысла засовывать это в переменную, можно сразу прокинуть

2021-06-03 10:19 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/ProfileForm/styles.module.scss
> +  & > * {
1/ написание стилей с * не самый лучший способ, тут явно можно обойти такое правило
2/ дублирование этого же css правила мне подсказывает о том что за это должен кто-то отвечать в 1м месте

2021-06-03 10:21 UTC, oleksandrbazil reviewed
посмотри на незакрытые комменты

2021-06-03 12:35 UTC, andrey-dihtiarov commented on src/pages/users/UserFormPage/AccountForm/index.jsx
> +        const { size } = value;
Cannot destructure property 'size' of 'object null' as it is null.
![image](https://user-images.githubusercontent.com/82100556/120645625-4b6a1200-c481-11eb-95f7-84291652524e.png)

2021-06-04 08:40 UTC, oleksandrbazil commented on src/pages/users/UserFormPage/AccountForm/index.jsx
> +        const { size } = value;
```js
.test('fileSize', 'File too large', (value) => {
      const { size } = value || {};
      return size ? size <= MAX_IMG_SIZE : true;
    })
    ```

2021-06-04 08:44 UTC, andrey-dihtiarov commented on src/components/NavButtons/index.jsx
> +const NavButtons = ({ isFirst, isLast, onBack }) => {
Понял. Перенес NavButtons в StepWizard

2021-06-04 08:44 UTC, andrey-dihtiarov commented on src/components/NavButtons/index.jsx
> +    <FlatButton type="submit" variant="success">
Да, смысла нету. Убрал

2021-06-04 08:45 UTC, andrey-dihtiarov commented on src/components/NavButtons/index.jsx
> +    <FlatButton type="button" variant="cancel" onClick={onBack}>
Да, могу. Добавил это

2021-06-04 08:48 UTC, andrey-dihtiarov commented on src/pages/users/UserFormPage/AccountForm/index.jsx
> +        const { size } = value;
👍

2021-06-04 08:48 UTC, andrey-dihtiarov commented on src/pages/users/UserFormPage/AccountForm/styles.module.scss
> +  & > * {
Переделал

2021-06-04 08:48 UTC, andrey-dihtiarov commented on src/pages/users/UserFormPage/ProfileForm/index.jsx
> +  const initValues = { firstName, lastName, email, birthDate, gender, address };
Убрал эту переменную, передаю сразу

2021-06-04 08:49 UTC, andrey-dihtiarov commented on src/pages/users/UserFormPage/ProfileForm/styles.module.scss
> +  & > * {
Переписал и убрал дублирование

2021-06-04 14:38 UTC, oleksandrbazil approved these changes

2021-06-04 14:38 UTC, merged